### PR TITLE
Lay groundwork for analytics subsystem

### PR DESCRIPTION
**Pull request by JamesCoburn246**
This PR only includes stubs for the UnityAnalytics functionality. The purpose of this PR is to seek feedback (and potentially testing) for some changes that I made to other systems.

1. `PlayerPrefs.DeleteAll()` was being called by the AchievementController. This would not only reset all player settings (e.g. sound volume), but also future `PlayerPrefs` set by the analytics subsystem. I added functionality to make achievements delete themselves from the `PlayerPrefs` system. https://github.com/Baconeta-Studios/setting-the-stage/commit/3fe932b986e52c3bc139e85a98db4925fd6261bd
2. While I was trying to understand the code to implement the first bulletpoint, I made some changes to make it easier to read. Some code was simplified; Some comments were added; Other generic cleanups were performed.
3. I added a utility class to store preprocessor directives as static variables to be referred to from other files, ensuring that they become more readable and maintainable. https://github.com/Baconeta-Studios/setting-the-stage/commit/ef19d3bdbdf58fd0c946872309f00e012d1d64df https://github.com/Baconeta-Studios/setting-the-stage/commit/93af6d7efcb436d7c4d7afe423768c1a35d9b4bf
4. I committed a question into a file to be reviewed. I didn't author the system and don't fully understand why the check is being made twice. I felt like it would be best to raise it to the attention of someone more familiar with the logic (@baconeta). https://github.com/Baconeta-Studios/setting-the-stage/commit/f11dbbce4487908b7a07ab9cde05218e4d911a82

This PR is only as urgent as merge-issues deem necessary.

Merging this PR will close https://github.com/Baconeta-Studios/setting-the-stage/issues/50

### CODE REVIEW

**Comment by baconeta** [comment]
I will temporarily add some comments and brief tidy ups to ensure the system compiles - have added TODOs in the obvious places where I commented out code

**Comment by baconeta** [comment]
Also note we are not currently using the achievement system yet - it's only here from the template code, but good idea to bring it up to speed

**Comment by baconeta** [comment]
Lastly, your beautiful tidy up the save system was nice but I think your IDE was telling you incorrectly about using _ prefix for the code - apparently for serialized fields we always use camelCase only
Anyway, there will be a code style guide coming soon which we will adhere to for the full game so I wouldn't get so picky on it atm

**Review by baconeta — CHANGES_REQUESTED** [review]
I definitely prefer to abstract the analytics away from the codebase wherever possible but I will say that if we get insane with our analytics in the future that UnityAnalytics is going to be a massive class.

My experience says to have a single event handling the analytics and let it take a dict of any length or null for sending analytics. I will make a proposed commit in about 20 mins and you let me know if you're happy with this or not - feel free to adjust or revert it

**Review by SabrinaTheCookie — APPROVED** [review]
Looks good - TODO is change PlayerPrefs to our StS save system. But that'll come after vertical slice.

**Review by baconeta — APPROVED** [review]
I'm now happy with this. It needs:

-Testing to make sure it hooks up with UA once we have the events in the dashboard
- Added Player UUID into the default analytics events 
- Implementation of all events and analytics
- Proper consenting system (we are almost there but might need a settings page to complete it)

**Comment by baconeta** [comment]
Merging this PR will close #50

**Pull request merged**
